@startuml
autonumber
actor "Laboratory Coordinator" as LabCod

activate LabCod
LabCod -> ":System" : Initiates the process of Importing Clinical Tests
activate ":System"

":System" --> LabCod : Asks to choose the File(s)
deactivate ":System"

LabCod -> ":System" : Selects the File(s)
activate ":System"

":System" --> LabCod : Requests confirmation
deactivate ":System"

LabCod -> ":System" : Confirms the data
activate ":System"
":System" --> LabCod : Informs the operation sucess.
deactivate ":System"

deactivate LabCod

@enduml