@startuml

class Company{
-String designation
+getTestStore()
}

class RecordTestResultsUI{

}

class RecordTestResultsController{
+getParameterList()
+AddResult(parameterSelected,result,metric)
}

class ParameterMapper{
+ToDTO(ParameterList)
}

class Test {
-code
-NhsCode
-createdAt
+AddResult(refValue,result,metric)
+getParameterList()
}

class TestStore{
+getTestByBarcode
}

class TestParameter{
+AddResult(refValue,result,metric)
}


class TestParameterResult{
-createdAt
-value
-metric
}

class Parameter{
-code
-shortName
-description
}

class ParameterDTO{
}

class ReferenceValue{

}

class TestType{
  -String code
  -String description
  -String collectingMethod
  -List<ParameterCategories> listOfParameterCategories
  +getExternalModule()

}

class ExternalModule2APIAdapter{
 +ReferenceValue getReferenceValue(Parameter param)
}

class ExternalModule3APIAdapter{
 +ReferenceValue getReferenceValue(Parameter param)
}

class CovidReferenceValues1APIAdapter{
 +ReferenceValue getReferenceValue(Parameter param)
}

class ExternalModuleAdapter2{
 +ReferenceValue getReferenceValue(Parameter param)
}

interface ExternalModule{
+getReferenceValue(Parameter param)
}



RecordTestResultsUI ..> RecordTestResultsController
RecordTestResultsUI ..> ParameterDTO
RecordTestResultsController ..> Company
RecordTestResultsController ..> ParameterMapper
RecordTestResultsController ..> Test
RecordTestResultsController ..> TestStore
Company ---> TestStore : uses
ParameterMapper ......> Parameter
ParameterMapper ..> ParameterDTO
TestType"*" -> "1" ExternalModule : makes use of
TestStore "1" -> "*" Test : conducts
Test "*" -> "1" TestType : is of
Test "1" ---> "1..*" TestParameter : requests analysis of
Parameter "1" <- "*" TestParameter : refers to
TestParameter "1" -> "0..1" TestParameterResult : contains
TestParameterResult "1" -> "1" ReferenceValue :records
CovidReferenceValues1APIAdapter ..|> ExternalModule
ExternalModule2APIAdapter ..|> ExternalModule
ExternalModule3APIAdapter ..|> ExternalModule



@enduml