@startuml
autonumber
'hide footbox
actor "Clinical Chemistry Technologist" as CCT

participant ": RecordTestResultsUI" as UI
participant ": RecordTestResultsController" as CTRL
participant ": Company" as Comp
participant "test: Test" as Test

activate CCT
CCT -> UI : asks to register the test results
activate UI
UI -> CCT : request the barcode number
deactivate UI
CCT -> UI : types requested data
activate UI
UI -> CTRL : getTestByBarcode()
activate CTRL
CTRL -> Comp :

CTRL -> UI : TestDTO
deactivate CTRL
loop *for each test parameter being analysed
UI -> CCT : shows a Parameter list
deactivate UI
CCT -> UI : selects test parameter
activate UI
UI -> CCT : request the result value and metric
deactivate UI
CCT -> UI : types requested data
activate UI
UI -> CTRL : addTestResult(parameterSelected,result,metric)
activate CTRL
CTRL -> Test : addTestResult(parameterSelected,result,metric)

CTRL --> UI : success
deactivate CTRL
UI --> CCT : success
deactivate UI


end





deactivate CCT
@enduml