@startuml
autonumber
'hide footbox
actor "Administrator" as ADMIN

participant ": OverviewUI" as UI
participant ": OverviewController" as CTRL
participant ": Company" as COMP
participant ": Overview" as OVERVIEW
participant ": TestStore" as TS
participant ": TestMapper" as tMAPPER
participant ": SubsequenceWithMaximumSum" as interface

activate ADMIN
ADMIN -> UI : Initiates the process of overviewing the tests
activate UI
UI --> ADMIN : Requests to delimit the period of dates to analyze
deactivate UI

ADMIN -> UI : Selects the dates and asks to see relative information
activate UI
UI -> CTRL : getIntervalTestList(initialDate,endDate)
activate CTRL

CTRL -> COMP : testStore = getTestStore()
activate COMP
deactivate COMP
CTRL -> TS : testList = getIntervalTestList(initialDate,endDate)
activate TS
deactivate TS
CTRL --> OVERVIEW** : create(initialDate,endDate, testList)
deactivate CTRL

deactivate CTRL
UI -> CTRL : numberOfClients = getNumberOfClients()
activate CTRL
CTRL -> OVERVIEW : getNumberOfClients()
activate OVERVIEW
deactivate OVERVIEW
deactivate CTRL

UI -> CTRL : numberOfTestsWaitingForResults = getNumberOfTestsWaitingForResults()
activate CTRL
CTRL -> OVERVIEW : getNumberOfTestsWaitingForResults()
activate OVERVIEW
deactivate OVERVIEW
deactivate CTRL

UI -> CTRL : numberOfTestsWaitingForDiagnosis = getNumberOfTestsWaitingForDiagnosis()
activate CTRL
CTRL -> OVERVIEW : getNumberOfTestsWaitingForDiagnosis()
activate OVERVIEW
deactivate OVERVIEW
deactivate CTRL

UI -> CTRL : totalNumberOfTestsProcessed = getTotalNumberOfTestsProcessed()
activate CTRL
CTRL -> OVERVIEW : getTotalNumberOfTestsProcessed()
activate OVERVIEW
deactivate OVERVIEW
deactivate CTRL

UI --> ADMIN : Shows successfully the relative information ( number of clients, number of tests Waiting for results,\n the number of tests Waiting for diagnosis, total number of tests processed \n in the laboratory in each day, week, month and year
deactivate UI
alt select option to evaluate performance
ADMIN -> UI : Asks to evaluate performance
activate UI
UI -> CTRL : getAvailableAlgorithms()
activate CTRL
CTRL -> OVERVIEW : getAvailableAlgorithms()
activate OVERVIEW
OVERVIEW --> CTRL : availableAlgorithmsList
deactivate OVERVIEW
CTRL --> UI : availableAlgorithmsList
deactivate CTRL
UI --> ADMIN : Shows available algorithms
deactivate UI

ADMIN -> UI : Selects the algorithm and asks for the least effective time
activate UI
UI -> CTRL : getSubsequenceWithMaximumSum()
activate CTRL
CTRL -> OVERVIEW : getSubsequenceWithMaximumSum()
activate OVERVIEW
OVERVIEW -> interface : getSubsequenceWithMaximumSum()
activate interface
interface --> OVERVIEW : subsequenceWithMaximumSum
deactivate interface
OVERVIEW --> CTRL : subsequenceWithMaximumSum
deactivate OVERVIEW
CTRL --> UI : subsequenceWithMaximumSum
deactivate CTRL
UI --> ADMIN : Shows successfully the least effective time
deactivate UI
end
deactivate ADMIN

@enduml