@startuml
autonumber
actor "User" as User

activate User
User -> ":System" : Initiates the process of overviewing the tests
activate ":System"

":System" --> User : Requests to delimit the period of dates to analyze
deactivate ":System"

User -> ":System" : Selects the dates and asks to see relative information
activate ":System"

":System" --> User : Shows successfully the relative information ( number of clients, number of tests Waiting for results,\n the number of tests Waiting for diagnosis, total number of tests processed \n in the laboratory in each day, week, month and year
deactivate ":System"
alt select option to evaluate performance
User -> ":System" : Asks to evaluate performance
activate ":System"
":System" --> User : Shows available algorithms
deactivate ":System"

User -> ":System" : Selects the algorithm and asks for the least effective time
activate ":System"
":System" --> User : Shows successfully the least effective time
deactivate ":System"
end
deactivate User

@enduml