@startuml
autonumber
actor "User" as User

activate User
User -> ":System" : asks to overview the tests
activate ":System"
":System" --> User : shows the number of clients
":System" --> User : shows the number of tests Waiting for results
":System" --> User : shows the number of tests Waiting for diagnosis
":System" --> User : shows the total number of tests processed \n in the laboratory in each day, week, month and year
deactivate ":System"

User -> ":System" : asks to evaluate performance
activate ":System"
":System" --> User : shows available algorithms
deactivate ":System"

User -> ":System" : selects the algorithm
activate ":System"
":System" --> User : requests to delimit the period of dates to analyze
deactivate ":System"

User -> ":System" : types the dates
activate ":System"
":System" --> User : shows dates and asks for confirmation
deactivate ":System"

User -> ":System" : asks for statistics and graphs
activate ":System"
":System" --> User : shows statistics and graphs
deactivate ":System"

User -> ":System" : confirms the data
activate ":System"
":System" --> User : informs operation success
deactivate ":System"

deactivate User

@enduml