@startuml


package ui {
class OverviewUI{}
}

package Controller{
class OverviewController{
+getIntervalTestList(initialDate,endDate)
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}

package model{
class Company{
+getTestStore()
}
class Overview{
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}



package store{
class TestStore{
+getIntervalTestList(initialDate,endDate)
}
}

package mappers{
class TestMapper{
}
}


package dto{
}

package interfaces{
interface SubsequenceWithMaximumSum{
+getSubsequenceWithMaximumSum()
}
}


OverviewUI ..> OverviewController

OverviewController ..> TestMapper
OverviewController ..> TestStore
OverviewController ..> Company
OverviewController ..> Test

Company -> Test
Company -> TestStore
Company..|>SubsequenceWithMaximumSum

TestMapper ..> TestDto
TestMapper ..> Test




@enduml