@startuml


package ui {
class OverviewUI{}
}

package Controller{
class OverviewController{
+getIntervalTestList(initialDate,endDate)
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}

package adapter{
class BenchmarkAdapter{
}

class BruteForceAdapter{
}
}

package model{
class Company{
+getTestStore()
}
class Test{
-client
-nhscode
-testParameterList
-stateOfTest
-internalCode
}
class Client{
}
class Overview{
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}



package store{
class TestStore{
+getIntervalTestList(initialDate,endDate)
}
class ClientStore{
}
}


package interfaces{
interface SubsequenceWithMaximumSum{
+getSubsequenceWithMaximumSum()
}
}


OverviewUI ..> OverviewController

OverviewController ..> TestStore
OverviewController ..> ClientStore
OverviewController ..> Company
OverviewController ..> Test
OverviewController ..> Overview

Company "1" ----> "1" TestStore : uses
TestStore "1" --> "*" Test : knows
ClientStore "1" --> "*" Client : knows

Overview "*" -->"1"  SubsequenceWithMaximumSum : makes use of

BenchmarkAdapter..|>SubsequenceWithMaximumSum
BruteForceAdapter..|>SubsequenceWithMaximumSum

@enduml