@startuml


package ui {
class OverviewUI{}
}

package Controller{
class OverviewController{
+getIntervalTestList(initialDate,endDate)
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}

package model{
class Company{
+getTestStore()
}
class Overview{
+getNumberOfClients()
+getNumberOfTestsWaitingForResults()
+getNumberOfTestsWaitingForDiagnosis()
+getTotalNumberOfTestsProcessed()
+getAvailableAlgorithms()
+getSubsequenceWithMaximumSum()
}
}



package store{
class TestStore{
+getIntervalTestList(initialDate,endDate)
}
}

package mappers{
class TestMapper{
}
}


package dto{
}

class SubsequenceWithMaximumSum{
+getSubsequenceWithMaximumSum()
}





@enduml