@startuml
autonumber
actor "User" as User

activate User
User -> ":System" : initiates the process of overviewing the tests
activate ":System"

":System" --> User : requests to delimit the period of dates to analyze
deactivate ":System"

User -> ":System" : types the dates and asks to see relative information
activate ":System"

":System" --> User : shows the relative information ( number of clients, number of tests Waiting for results,\n the number of tests Waiting for diagnosis, total number of tests processed \n in the laboratory in each day, week, month and year
deactivate ":System"

User -> ":System" : asks to evaluate performance
activate ":System"
":System" --> User : shows available algorithms
deactivate ":System"

User -> ":System" : selects the algorithm and asks for statistics and graphs
activate ":System"
":System" --> User : shows statistics and graphs
deactivate ":System"

deactivate User

@enduml