@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":RegisterEmployeeUI" as UI
participant ":RegisterEmployeeController" as CTRL
participant ":Company" as COMP
participant "store : OrganizationRoleStore" as ORGSTORE

participant "store : EmployeeStore" as STORE
participant "AuthFacade" as FCD



activate ADM
ADM -> UI : starts the creation of a new employee
activate UI
UI -> CTRL: or = getOrganizationRoles()
activate CTRL
CTRL -> COMP : store = getOrganizationRoleList()
activate COMP
COMP -> ORGSTORE : or = getOrganizationRoles()
activate ORGSTORE
UI-->ADM : show the employees roles
deactivate ORGSTORE
deactivate COMP
deactivate CTRL
deactivate UI



ADM -> UI : select the desired role
activate UI
UI -> CTRL : createOrganizationRole(selectedRole)
activate CTRL
CTRL -> COMP : store = getOrganizationRolesStore()
activate COMP
CTRL -> ORGSTORE : or = createOrganizationRole(selectedRole)

activate ORGSTORE

ORGSTORE --> "or : Organization Role"** : createOrganizationRole(selectedRole)
deactivate ORGSTORE


alt or = specialist doctor
UI --> ADM : request data (name, address, phoneNumber, email,socCode, doctorIndexNumber)
else
UI --> ADM : request data (name, adress, phoneNumber, email, socCode)

deactivate COMP
deactivate CTRL
deactivate UI
end


ADM -> UI : types requested data
activate UI
alt or = specialist doctor
UI -> CTRL : createEmployee(name, adress, phoneNumber, email, socCode, or, doctorIndexNumber)
activate CTRL
CTRL -> COMP : e = createEmployee(name, adress, phoneNumber, email, socCode, or, doctorIndexNumber)
deactivate CTRL
activate COMP
COMP -> STORE : store = getEmployeeStore()
deactivate COMP
activate STORE
STORE -> "emp : specialistDoctor"** : create(name, adress, phoneNumber, email, socCode, or, doctorIndexNumber)
deactivate STORE
else
UI -> CTRL : createEmployee(name, adress, phoneNumber, email, socCode, or)
activate CTRL
CTRL -> COMP : e = createEmployee(name, adress, phoneNumber, email, socCode, or)
deactivate CTRL
activate COMP
COMP -> STORE : store = getEmployeeStore()
deactivate COMP
activate STORE
STORE -> "emp : Employee"** : create(name, adress, phoneNumber, email, socCode, or)
deactivate STORE
end

UI --> ADM : show the data and request comfimation
deactivate UI

ADM ->UI : confirms the data
activate UI
UI -> CTRL : saveEmployee()
activate CTRL
CTRL -> STORE : saveEmployee(emp)

activate STORE

STORE ->STORE : validateEmployee(emp)
activate STORE
deactivate STORE

STORE ->STORE : addEmployee(emp)
activate STORE
deactivate STORE
UI --> ADM : informs operation success
deactivate CTRL
deactivate UI





@enduml