@startuml
class Company
class ParameterStore
class ParameterCategoryStore
class Parameter
class ParameterCategory

class Company{
-designation
+getParameterStore()
+getParameterCategoryStore()
+getTestTypeStore()
}

class CreateParameterCategoryUI {
+createParameterCategory()

}


class ParameterStore{
+createParameter(name, parameterValue, category)
+validateParameter(pc)
+saveParameter(pc)
+getParameterByName(name)
+getParametersByCategory(category)
}

class ParameterCategoryStore{
+createCategory(code, name)
+validateCategory(c)
+saveCategory(c)
+getParameterCategoryStore(code)
}

class Parameter {
-name
-parameterValue
+Parameter(name, parameterValue, category)
}

class ParameterCategory {
-code
-name
+ParameterCategory(code, name)
}



Company "1"-->"1" ParameterStore : uses
Company "1"-->"1" ParameterCategoryStore : uses
ParameterCategoryStore "1"-->"1" ParameterCategory: adopts
ParameterStore "1"-->"*" Parameter: capable of analysing
Parameter "*"-->"1" ParameterCategory : presented under



@enduml