@startuml
autonumber
'hide footbox
actor "Administrator" as Adm

participant ": CreateParameterCategoryUI" as UI
participant ": CreateParameterCategoryController" as CTRL
participant ": Company" as Comp
participant "store: ParameterCategoryStore" as str
participant "pc: ParameterCategory" as Cat

activate Adm
Adm-> UI: starts new parameter category
activate UI
UI --> Adm : request data (name, code)
deactivate UI
Adm -> UI: types requested data
activate UI

UI -> CTRL : createParameterCategory(name,code)
activate CTRL
CTRL -> Comp : store = getParameterCategoryStory()
activate Comp
deactivate Comp
CTRL -> str : pc = createParameterCategory(name,code)
activate str
str -> Cat** : create(name,code)
deactivate str

CTRL -> str : validateParameterCategory(pc)
activate str
deactivate str
deactivate CTRL

UI --> Adm : shows the data and requests a confirmation
deactivate UI
Adm -> UI: confirms the data
activate UI

UI -> CTRL: saveParameterCategory()
activate CTRL
CTRL -> str: validateParameterCategory(pc)
activate str
str -> str : validateParameterCategory(pc)
activate str
deactivate str
str ->str : addParameterCategory(pc)
activate str
deactivate str
deactivate str
deactivate CTRL
UI --> Adm : informs operation success
deactivate UI
deactivate Adm
@enduml