@startuml
left to right direction
skinparam classAttributeIconSize 0

class Company{
-String name
-String designation
-category
-address
-headquarters
}


class CreateParameterUI{
}

class CreateParameterController{
+getParameterCategories()
+createParameter(code,shortName,description,selectedCategory)
+saveParameter()
}

class Parameter{
- int code
- String shortName
- String description
+ create(code,shortName,description,selectedCategory)

}

class ParameterStore {
+createParameter(code,shotName,description,selectedCategory)
+validateParameter(p)
+saveParameter(p)
+getParameterByCode(p)
+getParameterByCategory(p)
}

class ParameterCategoryStore {
+getCategory(selectedCategory)
}

CreateParameterUI ..> CreateParameterController
CreateParameterController ..> Company
ParameterStore ..> Parameter : Capable of analyzing
Parameter ..> ParameterCategoryStore
Company "1" --> "1" ParameterStore : uses

@enduml