@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as ADM

participant ": CreateParameterUI" as UI
participant ": CreateParameterController" as CTRL
participant ": Company" as COMP
participant "parameterCategoryDto : ParameterCategoryDto" as PARCATDTO
participant "listParameterCategory : List<ParameterCategory>" as LISTCAT
participant "listParameterCategoryDto : List<ParameterCategoryDto>" as LISTCATDTO
participant ": store: ParameterStore" as STORE
participant ": ParameterCategoryMapper" as MAPPER
participant ": ParameterCategoryStore" as PC
participant "p: Parameter" as PRMT





activate ADM
ADM -> UI: starts new parameter
activate UI
UI -> CTRL : listParameterCategoryDto = getListParameterCategoryDto()
activate CTRL
CTRL -> COMP : store = getParameterCategoriesStore()
CTRL -> STORE : listOrgRoles = getListOfOrganizationRoles()
activate STORE
deactivate CTRL
deactivate STORE


UI --> ADM : shows the categories available
deactivate UI






ADM -> UI: inserts the category(selectedCategory)
activate UI
UI--> ADM : request data (code, shortName, description)
deactivate UI
ADM -> UI : types request data

activate UI
UI -> CTRL : createParameter(code, shortName, description, selectedCategory)
activate CTRL
CTRL -> COMP : toDTO()
activate COMP
COMP -> MAPPER : toDTO(listParameterCategory)
deactivate COMP
activate MAPPER
MAPPER->MAPPER : ParameterCategoriesDto = toDto(ParameterCategory)
MAPPER --> CTRL : ParameterCategory
deactivate MAPPER
CTRL -> STORE : t = createParameter(code,shortName,description,selectedCategory)
activate STORE
STORE -> PRMT** : create(code,shortName,description,categoryCode)
deactivate STORE
CTRL -> STORE : validateParameter(p)
activate STORE
deactivate STORE
deactivate CTRL
UI --> ADM : shows all data and asks for confirmation
deactivate UI








ADM -> UI: confirms the data
activate UI
activate CTRL
UI -> CTRL : saveParameter()
activate STORE
CTRL -> STORE : saveParameter(p)
STORE -> STORE : validateParameter(p)
activate STORE
deactivate STORE
STORE ->STORE : addParameter(p)
activate STORE
deactivate STORE
deactivate STORE
deactivate STORE
CTRL --> UI : result
deactivate CTRL
UI --> ADM : informs the operation success
deactivate UI
deactivate ADM

@enduml