@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as ADM

participant ": CreateParameterUI" as UI
participant ": CreateParameterController" as CTRL
participant ": Company" as COMP
participant ": store: ParameterStore" as STORE
participant ": ParameterCategoryMapper" as MAPPER
participant ": ParameterCategoryStore" as PCSTORE
participant "p: Parameter" as PRMT
participant "listParameterCategory : \n List<ParameterCategory>" as LISTPC
participant "parameterCategoryDto : \n ParameterCategoryDto" as PCDTO
participant "listParameterCategoryDto : \n List<ParameterCategoryDto>" as LISTPCDTO



activate ADM
ADM -> UI: starts new parameter
activate UI
UI -> CTRL : listParameterCategoryDto = getListParameterCategoryDto()
activate CTRL
CTRL -> COMP : store = getParameterCategoriesStore()
activate COMP
deactivate COMP
CTRL -> PCSTORE : listParameterCategory = getListOfParameterCategory()
activate PCSTORE
deactivate PCSTORE
CTRL -> COMP : toDTO()
activate COMP
COMP -> MAPPER : toDTO(listParameterCategory)
deactivate COMP
activate MAPPER

loop for each object in listParameterCategory
MAPPER -> LISTPC : ParameterCategory = getParameterCategories(i)
activate LISTPC
deactivate LISTPC
MAPPER-> PCDTO : ParameterCategoriesDto = toParameterCategoryDto(ParameterCategory)
activate PCDTO
deactivate PCDTO
MAPPER-> LISTPCDTO : addParameterCategoryDto(ParameterCategoryDto)
activate LISTPCDTO
deactivate LISTPCDTO
end
MAPPER --> CTRL : listParameterCategoryDto
deactivate MAPPER
deactivate CTRL



UI --> ADM : shows the categories available
deactivate UI






ADM -> UI: inserts the category(selectedCategory)
activate UI
UI--> ADM : request data (code, shortName, description)
deactivate UI
ADM -> UI : types request data

activate UI
UI -> CTRL : createParameter(code, shortName, description, selectedCategory)
activate CTRL

CTRL -> STORE : t = createParameter(code,shortName,description,selectedCategory)
activate STORE
STORE -> PRMT** : createParameter(code,shortName,description,categoryCode)
deactivate STORE
CTRL -> STORE : ValidateParameter(p)
activate STORE
STORE -> STORE : validateParameter(p)
activate STORE
deactivate STORE

CTRL -> STORE : getParameterData(p)
STORE -> PRMT : code = getParameterByCode(p)
activate PRMT
STORE -> PRMT : category = getParameterByCategory(p)
deactivate PRMT

deactivate CTRL
deactivate STORE
UI --> ADM : shows all data and asks for confirmation
deactivate UI








ADM -> UI: confirms the data
activate UI
UI -> CTRL : saveParameter()
activate CTRL
CTRL -> STORE : saveParameter(p)
activate STORE
STORE ->STORE : addParameter(p)
activate STORE
deactivate STORE
deactivate STORE
deactivate STORE
CTRL --> UI : result
deactivate CTRL
UI --> ADM : informs the operation success
deactivate UI
deactivate ADM

@enduml