package app.domain.shared;

public interface DefaultOrgRoles {

    String[] ORGANIZATIONROLES = {"ADMINISTRATOR", "RECEPTIONIST", "MEDICAL LAB TECHNICIANS", "CLINICAL CHEMISTRY TECHNICIANS", "SPECIALIST DOCTOR", "LABORATORY COORDINATOR"};

}
