@startuml
'https://plantuml.com/class-diagram
hide methods
skinparam classAttributeIconSize 0

class Company
class Parameter
class ParameterCategory
class Employee


class Company{
-name
-designation
-category
-address
-headquarters
}

class Parameter{
-code
-designation
-description
}

class ParameterCategory{
-code
-description
-nhsid
}

class Employee {
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}


Company "1"---"1..*" Parameter : capable of analyzing >
Company "1"---"1..*" ParameterCategory : adopts >
Company "1"---"1..*" Employee : employ >
Parameter "*"---"1" ParameterCategory : presented under >
Parameter "*" --- "1" Employee : specified by >
ParameterCategory "*"--"1" Employee : specified by >


@enduml