@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Clinical Chemistry Technologist" as CCT

participant ": SeeTestsUI" as UI
participant ": SeeTestsController" as CTRL
participant ": Company" as Comp
participant "clStore: ClientsStore" as CStore
participant "mapper: ClientMapper" as ClMapper
participant "tstore : TestStore" as tStore
participant "tMapper : TestMapper" as TMapper


activate CCT
CCT -> UI : asks to consult the tests performed by a particular client
activate UI
UI -> CTRL : getClientslist()
activate CTRL
CTRL -> Comp : clstore = getClientStore()
activate Comp
deactivate Comp
CTRL -> CStore : getClientList()
activate CStore
CStore --> CTRL : ClientsList
deactivate CStore
CTRL -> ClMapper : toDTO(ClientsList)
activate ClMapper
ClMapper --> CTRL : ClientsListDTO
deactivate ClMapper
CTRL --> UI : ClientsListDTO
deactivate CTRL
UI -> CCT : show a list of clients and asks to select one
deactivate UI

CCT -> UI : select the desired client
activate UI
UI -> CTRL : getTestsByClient(selectedClient)
activate CTRL
CTRL -> tStore : getTestsByClient(selectedClient)
activate tStore
tStore --> CTRL : ListOfTests
deactivate tStore
CTRL -> TMapper : toDTO(ListOfTests)
activate TMapper
TMapper --> CTRL : ListOfTestsDTO
deactivate TMapper
CTRL --> UI :ListOfTestsDTO
deactivate CTRL
UI -> CCT : show the historical tests performed by that client
deactivate UI




@enduml