@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Client{
 - name
 - email
 - phoneNumber
 - sex
 - tin
 - birthDate
 - nhsNumber
 - citizenCardNumber
}
class Test{
-internalCode
-nhsCode
-description
-dateOfSampleCollected
-timeOfSampleCollected
-dateOfSampleAnalysis
-timeOfSampleAnalysis
-state
}
Test "1..*"---"1" Client : associated a <


@enduml