@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-name
-designation
-category
-address
-headquarters
}

class Employee{
-name
-address
-phoneNumber
-e-mail
-employeeId
-organizationRole
-socCode
}

class TestType{
-designation
}

class SpecialistDoctor  {
-doctorIndexNumber
}

class Laboratory{
-name
-address
-phoneNumber
-TIN
}

class Barcode{
-code
}

class Report{
-diagnosis
-date
-time
}

class Sample{
-collection date
}

class Test{
-internalCode
-nhsCode
-description
}

class Client{
 - Name
 - Email
 - Phone Number
 - Sex
 - TIN
 - Birth Date
 - NHS Number
 - Citizen Card Number
}

class Receptionist{

}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalAnalyses{
-date
-time
}

class Parameter{
-name
-parameterValue
}

class Category{
-name
}

class MedicalLabTechnician{

}

class ChemicalLaboratory{

}

class ClinicalChemistryTechnologist{

}

class LabOrder{

}

class LaboratoryCoordinator{

}

class Administrator{

}

class ExternalAPI{

}

class ExternalModulo {
-ReferenceValue
}

class NhsAPI{

}

class BloodTest{

}

class Covid19Test{
}
class DailyReport{
-Covid19Data
}


Company "1"----"*" Employee
ClinicalAnalysisLaboratory "*"----"1" Laboratory : is a >
ChemicalLaboratory "1"---"1" Laboratory : is a >
MedicalLabTechnician "1"---"1" Employee : is a >
Administrator "1"---"1" Employee : is a >
ClinicalChemistryTechnologist "1"---"1" Employee : is a >
Receptionist "1"---"1" Employee : is a >
Receptionist "1"----"*" Client : register a >
Receptionist "1"----"*" Test : register >
Client "1"----"1..*" LabOrder : has a >
LabOrder "1"----"1" Test : order a >
LabOrder "*"----"*" Parameter: contain the >
Test "*"----"1" TestType : is of >
Test "1"----"1..*" Sample : needs >
TestType "*"----"1..*" Parameters : contain >
MedicalLabTechnician "1"----"*" Sample : collect >
MedicalLabTechnician "1"----"*" Test: registers the >
Sample "*"----"1" ClinicalChemistryTechnologist : < receives
Sample "1"----"1" Barcode : has a >
Barcode "*"----"1" ExternalAPI : generated by >
ClinicalChemistryTechnologist "*"----"1" ChemicalLaboratory : work in >
ClinicalChemistryTechnologist "1"----"*" ChemicalAnalyses : perform >
Category "*"----"1" Administrator : < create
Parameters "*"----"1" Category : under >
Parameters "*"----"1"Administrator : < create
SpecialistDoctor "1"----"1" Employee : is a >
SpecialistDoctor "1"----"*" ChemicalAnalyses : analyzes >
SpecialistDoctor "1"----"*" Report : write >
LaboratoryCoordinator "1"----"1" Employee : is a >
LaboratoryCoordinator "1"----"*" Report : validates >
LaboratoryCoordinator "1"----"*" ChemicalAnalyses : validates >
Report "*"--"1" ExternalModulo: verified by >
Covid19Test "1"----"1" TestType : is a >
BloodTest "1"----"1" TestType : is a >
Covid19Test "1"----"1" Parameters : mesure >
BloodTest "1..*"----"1..*" Parameters : mesure >
Covid19Test "*"----"1" DailyReport : generate >
DailyReport "*"----"1" NhsAPI : send with >
Receptionist "1..*"----"1" ClinicalAnalysisLaboratory : works in >




@enduml