@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-name
-designation
-category
-address
-headquarter
}

class Employee{
-name
-address
-phoneNumber
-e-mail
-employeeId
-organizationRole
-socCode
}

class TestType{
-designation
}

class Doctor{
-doctorIndexNumber
}

class Laboratory{
-name
-address
-phoneNumber
-TIN
}

class Barcode{
-code
}

class Report{
-diagnosis
}

class Sample{
-collection date
}

class Test{
-internalCode
-nhsCode
-description
}

class Client{
 - Name
 - Email
 - Phone Number
 - Sex
 - TIN
 - Birth Date
 - NHS Number
 - Citizen Card Number

}

class Receptionist{

}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalAnalyses{
-date
-time
}

class Report{
-date
-time
}

class ReferenceValues{

}

class Barcode{

}

class Parameters{

}

class Category{

}

class MedicalLabTechnician{

}

class Chemical_Laboratory{

}

class Clinical_Chemistry_Technologist{

}

class LabOrder{

}

class Laboratory_Coordinator{

}

class Administrator{

}

class External_API{

}

class API {

}


Company "1"---"*" Employee : knows >
Company "1"--"*" Laboratory : owns >
Company "1" -- "*" Test: performs >
ClinicalAnalysisLaboratory "*"---"1" Laboratory : is a >
Chemical_Laboratory "1"--"1" Laboratory : is a >
MedicalLabTechnician "1"--"1" Employee : is a >
Administrator "1"--"1" Employee : is a >
Clinical_Chemistry_Technologist "1"----"1" Employee : is a >
Receptionist "1"--"1" Employee : is a >
Receptionist "1"---"*" Client : register a >
Receptionist "1"-"*" Test : register >
Client "1"--"1..*" LabOrder : has a >
LabOrder "1"--"1" Test : order a >
LabOrder "*" -- "*" Parameter: contain the >
Test "*"---"1" TestType : is of >
Test "1"---"1..*" Sample : needs >
TestType "*"--"1..*" Parameters : contain >
MedicalLabTechnician "1"---"*" Sample : collect >
MedicalLabTechnician "1" -- "*" Test: registers the >
Sample "*"----"1" Clinical_Chemistry_Technologist : < receives
Sample "1"--"1" Barcode : has a >
Barcode "*"--"1" External_API : generated by >
Clinical_Chemistry_Technologist "*"--"1" Chemical_Laboratory : work in >
Clinical_Chemistry_Technologist "1"--"*" ChemicalAnalyses : perform >
Category "*"--"1" Administrator : < create
Parameters "*"--"1" Category : under >
Parameters "*"---"1"Administrator : < create
Doctor "1"---"1" Employee : is a >
Doctor "1"-"*" ChemicalAnalyses : analyzes >
Doctor "1"---"*" Report : write >
Laboratory_Coordinator "1"--"1" Employee : is a >
Laboratory_Coordinator "1"--"*" Report : validates >
Laboratory_Coordinator "1"---"*" ChemicalAnalyses : validates >
ChemicalAnalyses "*"--"*" ReferenceValues : compared with >
Report "*" -- "1" API: verified by >









@enduml