@startuml

class ValidateWorkUI{
}

class ValidateWorkController{
+getTestToValidateList()
+showRegistrationDate(selectedTest)
+showChemicalAnalysisDate(selectedTest)
+showDiagnosisDate(selectedTest)
+showDates()
+recordValidationDate()
+notifyTheClient()
}

class Company{
-String name
-String shortName
-category
-address
-headquarters
--
+getTestStore()
}

class TestStore {
+getTestHasReportList()
+getTestByInternalCode(code)
}

class TestMapper{
List<TestDto> listTestsToValidateDto
List<Test> listTestWaitingForResult
List<TestDto> listDatesDto
testDto : TestDto
registrationDateDto : RegistrationDateDto
chemicalAnalysisDateDto : ChemicalAnalysisDateDto
diagnosisDateDto : DiagnosisDateDto
--
+toDto(testHasReportList)
+dateToDto()
+createDateDto(nhsCode,testCode)
+addDateDto(testDto)
}


class LabCoordinatorValidation {
-dateAndTime
--
+createTestValidation(selectedTest)
+recordValidationDate()
}

class Test{
-internalCode
-nhsCode
-description
--
+getNhsCode()
+getInternalCode()
+getRegistrationDate()
+getChemicalAnalysisDate()
+getDiagnosisDate()
}

class EmailNotification{
+notifyByEmail(Client)
}

class SMSNotification{
+notifyBySMS(Client)
}

class Client{
}


ValidateWorkUI .> ValidateWorkController : uses

ValidateWorkController ..> Company : uses
ValidateWorkController ..> TestStore : uses
ValidateWorkController ..> TestMapper : uses
ValidateWorkController ..> LabCoordinatorValidation : uses
ValidateWorkController ..> EmailNotification : uses
ValidateWorkController ..> SMSNotification : uses

Company "1"---"1..*" Test : performs >

LabCoordinatorValidation "1"---"1" Test : associated to

TestMapper ..> Test : uses

EmailNotification "1"---"1" Test : associated to >

SMSNotification "1"---"1" Test : associated to >

Client "*"---"1..*" SMSNotification : receives >
Client "*"---"1..*" EmailNotification : receives >


@enduml