@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-name
-designation
-category
-address
-headquarters
}

class Employee{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class TestType{
-designation
-collectingMethod
}

class SpecialistDoctor  {
-doctorIndexNumber
}

class Laboratory{
-name
-address
-phoneNumber
-tin
}

class Barcode{
-code
}

class DoctorReport{
-diagnosis
-date
-time
}

class Sample{
}

class Test{
-internalCode
-nhsCode
-description
}

class Client{
 - name
 - email
 - phoneNumber
 - sex
 - tin
 - birthDate
 - nhsNumber
 - citizenCardNumber
}

class Receptionist{

}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalAnalyses{
-date
-time
}

class Parameter{
-name
-parameterValue
}

class ParameterCategory{
-name
-code
}

class MedicalLabTechnician{

}

class ChemicalLaboratory{

}

class ClinicalChemistryTechnologist{

}

class LabOrder{

}

class LaboratoryCoordinator{

}

class Administrator{

}

class ExternalAPI{

}

class ExternalModule {
-referenceValue
}

class NhsAPI{

}

class BloodTest{

}

class Covid19Test{
}

class Covid19Report{
-covid19Data
}

class SMS{
-message
}

class Email{
-message
}

class Results{

}


Company "1"----"*" Employee : knows >
Company "1"----"1..*" Laboratory : owns >
Company "1"----"1..*" Administrator : knows >
ClinicalAnalysisLaboratory --|> Laboratory
ChemicalLaboratory --|> Laboratory
MedicalLabTechnician --|> Employee
ClinicalChemistryTechnologist --|> Employee
Receptionist --|> Employee
Receptionist "1"----"*" Client : registers >
Receptionist "1"----"*" Test : registers >
Client "1"----"1..*" LabOrder : has a >
LabOrder "1"----"1" Test : orders >
LabOrder "*"----"*" Parameter: contain the >
Test "*"----"1" TestType : < is a
TestType "1"----"1..*" Sample : needs >
TestType "*"----"1..*" Parameter : measure >
MedicalLabTechnician "1"----"*" Sample : collects >
MedicalLabTechnician "1"----"*" Test: registers locally the >
Sample "1"----"1" Barcode : has a >
Barcode "*"--"1" ExternalAPI : generated by >
ClinicalChemistryTechnologist "*"----"1" ChemicalLaboratory : works in >
ClinicalChemistryTechnologist "1"--"*" ChemicalAnalyses : performs >
ChemicalAnalyses "1"--- "1" Results : generates >
ParameterCategory "*"----"1" Administrator : < creates
Parameter "*"----"1" ParameterCategory : under >
Parameter "*"----"1"Administrator : < creates
Parameter "1" ---- "1" ChemicalAnalyses : analyze by >
SpecialistDoctor --|> Employee
SpecialistDoctor "1"----"*" Results : analyzes >
SpecialistDoctor "1"----"*" DoctorReport : write >
LaboratoryCoordinator --|> Employee
LaboratoryCoordinator "1"----"*" DoctorReport : validates >
LaboratoryCoordinator "1"----"*" ChemicalAnalyses : validates >
LaboratoryCoordinator "1"-------------"*" Results : validates >
DoctorReport "*"--"1" ExternalModule: verified by >
Covid19Test "1"----"1" TestType : is a >
BloodTest "1"----"1" TestType : is a >
Covid19Test "*"----"1" Covid19Report : generates >
Covid19Report "*"----"1" NhsAPI : send with >
Receptionist "1..*"----"1" ClinicalAnalysisLaboratory : works in >
ClinicalAnalysisLaboratory "1..*"----"*" Test : performs >
MedicalLabTechnician "1..*"-"1" ClinicalAnalysisLaboratory : works in >
LabOrder "1"-"1" TestType : contains >
MedicalLabTechnician "1"--"*" Client : call >
Client "1"--"1..*" Sample : provides >
Sample "1..*"---"1" ChemicalLaboratory : send to >
ClinicalChemistryTechnologist "1"-----"*" ChemicalAnalyses : registers >
Test "1..*"----"1" Client : associated with >
TestType "1..*"----"1..*" ParameterCategory : contains >
Sample "1..*"----"1" Test : associated with >
ClinicalChemistryTechnologist ---- Sample : receives >
LaboratoryCoordinator "1"---"*" TestType : validates >
MedicalLabTechnician "1"----"1..*" Sample : records >
Client "*"--"1" SMS : receives >
Client "*"--"1" Email : receives >


@enduml
