@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-designation
}

class Laboratory{
-name
-address
-phoneNumber
-tin
}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalLaboratory{
}

class Administrator{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class Employee{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class Receptionist{
}

class Client{
 - name
 - email
 - phoneNumber
 - sex
 - tin
 - birthDate
 - nhsNumber
 - citizenCardNumber
}

class Test{
-internalCode
-nhsCode
-description
-dateValidationLabCordinator
-timeValidationLabCordinator
}

class MedicalLabTechnician{
}

class Sample{
-date
-time
}

class TestType{
-code
-description
-collectingMethod
}

class Parameter{
-code
-designation
-description
}

class ParameterResult{
-parameterValue
}

class ParameterCategory{
-name
-code
}

class ChemicalAnalysis{
-date
-time
}

class LabOrder{
}

class Barcode{
-code
}

class ExternalApi{
}

class ClinicalChemistryTechnologist{
}

class SpecialistDoctor{
-doctorIndexNumber
}

class MedicalReport{
-diagnosis
-date
-time
}

class ExternalModule{

}

class ReferenceValue{
-lowerLimitValue
-upperLimitValue
}

class LaboratoryCoordinator{
}

class NhsApi{
}

class Covid19Report{
}

class EmailResult{
-message
}

class SMSResult{
-message
}

class EmailLogin {
-password
}

Company "1"----"1..*" Laboratory : owns >
Company "1"----"1..*" Administrator : has >
Company "1"----"*" Employee : knows >
Company "1"----"*" Parameter : capable of analyzing >
Company "1"----"*" ParameterCategory : adopts >
Company "1"----"*" Test : performs >
Company "1"----"*" TestType : conducts >
Company "1"----"1" ExternalApi : resort to >
Company "1"-----"1" ExternalModule : resort to >
Company "1"----"1" NhsApi : resort to >

ClinicalAnalysisLaboratory ----|> Laboratory
ClinicalAnalysisLaboratory "1.."----"1..*" TestType : perform >

ChemicalLaboratory ----|> Laboratory
ChemicalLaboratory "*"----"*" ChemicalAnalysis : perform >

Administrator "1"----"*" Employee : register the >
Administrator "1"----"*" ClinicalAnalysisLaboratory : register a >
Administrator "*"----"*" TestType : specifies the >
Administrator "*"----"*" Parameter : specifies the >
Administrator "*"----"*" ParameterCategory : specifies the >

Receptionist -----|> Employee
Receptionist "1"----"*" Client : register the >
Receptionist "*"----"1" ClinicalAnalysisLaboratory : work in >
Receptionist "1"----"*" Test : register a >

Test"*"----"*" Client : associated a >
Test "*"----"1..*" Sample : request  >
Test "*"----"1..*" Parameter : measure >
Test "*"----"1" TestType : is of >
Test "*" ---- "1" ChemicalAnalysis : request >
Test "*" ---- "1" MedicalReport : request >

MedicalLabTechnician ----|> Employee
MedicalLabTechnician "*"----"1" ClinicalAnalysisLaboratory : work in >
MedicalLabTechnician "1"----"*" Sample : record the >
MedicalLabTechnician "1"----"*" Sample : collects >
MedicalLabTechnician "1"----"*" Test : register locally the >
MedicalLabTechnician "1"----"*" Client : call >

Parameter "*"----"1" ParameterCategory : presented under >
Parameter "1" ---- "1" ChemicalAnalysis : analyze by >

ParameterCategory "*"----"*" TestType : has a set of <

ParameterResult "1..*" ---- "1" Test : associated >
ParameterResult "1" ---- "1" Parameter : associated >

Sample "*"----"1" ChemicalLaboratory : sent to >
Sample "1"----"1" Test : associated >
Sample "*"----"1" Barcode : identified by >

Barcode "*"----"1" ExternalApi : generated by >

Client "1"-----"1..*" LabOrder : has a >
Client "1"----"1..*" Sample : provides >
Client "*"----"1" SMSResult : receives >
Client "*"----"1" EmailResult : receives >
Client "*"----"1" EmailLogin : receives >

LabOrder "*"----"1" Test : orders a >
LabOrder "*"----"1" TestType : contains the >
LabOrder "*"----"1..*" Parameter : contains the >

ChemicalAnalysis "1" ---- "1..*" Sample : analyzes >
ChemicalAnalysis "1"----"1..*" ParameterResult: generates >

ClinicalChemistryTechnologist ----|> Employee
ClinicalChemistryTechnologist "*"----"1" ChemicalLaboratory : works in >
ClinicalChemistryTechnologist "1"----"*" ChemicalAnalysis : performs >
ClinicalChemistryTechnologist "1"----"1..*" ParameterResult: register the >

SpecialistDoctor ----|> Employee
SpecialistDoctor "1"----"1..*" ParameterResult : analyzes
SpecialistDoctor "1"----"*" MedicalReport: write the >

MedicalReport "1..*"----"*" Client : delivered to >
MedicalReport "*"----"1..*" ParameterResult : contains >

ExternalModule "1"----"*" MedicalReport : validates >
ExternalModule "1"----"1..*" ReferenceValue : contains >

LaboratoryCoordinator ----|> Employee
LaboratoryCoordinator "1"----"*" MedicalReport : validates >
LaboratoryCoordinator "1"----"*" ChemicalAnalysis : validates >
LaboratoryCoordinator "1"----"1..*" ParameterResult : validates >

NhsApi "1"----"*" Covid19Report : send the >

@enduml