@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-name
}

class Laboratory{
-name
-address
-phoneNumber
-tin
}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalLaboratory{
}

class Administrator{
}

class Employee{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class Receptionist{
}

class Client{
 - name
 - email
 - phoneNumber
 - sex
 - tin
 - birthDate
 - nhsNumber
 - citizenCardNumber
}

class Test{
-internalCode
-nhsCode
-description
}

class MedicalLabTechnician{
}

class Sample{
}

class TestType{
-code
-description
-collectingMethod
}

class Parameter{
-name
-parameterValue
}

class ParameterCategory{
-name
-code
}

class ChemicalAnalysis{
-date
-time
}

class LabOrder{
}

class ChemicalResult{
}

class Barcode{
-code
}

class ExternalApi{
}

class ClinicalChemistryTechnologist{
}

class SpecialistDoctor{
-doctorIndexNumber
}

class MedicalReport{
-diagnosis
-date
-time
}

class ExternalModule{
-referenceValue
}

class LaboratoryCoordinator{
}

class NhsApi{
}

class Covid19Report{
}

class Email{
-message
}

class SMS{
-message
}

Company "1"----"1..*" Laboratory : owns >
Company "1"----"1..*" Administrator : has >
Company "1"----"*" Employee : knows >
ClinicalAnalysisLaboratory ----|> Laboratory
ChemicalLaboratory ---|> Laboratory
Administrator "1"----"*" Employee : register the >
Receptionist -----|> Employee
Receptionist "1"----"*" Client : register the >
Receptionist "*"----"1" ClinicalAnalysisLaboratory : work in >
Receptionist "1"----"*" Test : register a >
Test"*"----"*" Client : associated a >
Administrator "1"----"*" ClinicalAnalysisLaboratory : register a >
MedicalLabTechnician ----|> Employee
MedicalLabTechnician "*"----"1" ClinicalAnalysisLaboratory : work in >
MedicalLabTechnician "1"----"*" Sample : record the >
Test "*"----"*" Sample : request  >
ClinicalAnalysisLaboratory "1.."----"1..*" Test : perform >
Administrator "*"----"*" TestType : specifies the >
Administrator "*"----"*" Parameter : specifies the >
Administrator "*"----"*" ParameterCategory : specifies the >
Parameter "*"----"1" ParameterCategory : under >
Test "*"----"1..*" Parameter : measure >
Test "*"----"1" TestType : is of >
ParameterCategory "*"----"*" TestType : associated with >
Company "1"----"*" Test : performs >
Company "1"----------"*" TestType : conducts >
MedicalLabTechnician "1"----"*" Sample : collects >
Sample "*"----"1" ChemicalLaboratory : sent to >
ChemicalLaboratory "*"----"*" ChemicalAnalysis : perform >
Client "1"-----"1..*" LabOrder : has a >
LabOrder "*"----"1" TestType : orders a >
LabOrder "*"----"1..*" Parameter : contains the >
MedicalLabTechnician "1"----"*" Test : register locally the >
ChemicalAnalysis "1"----"1" ChemicalResult : generates >
Parameter "1" ----- "1" ChemicalAnalyses : analyze by >
Parameter "1..*"----"*" ChemicalResult : evaluated in >
Sample "1"----"1" Test : associated >
Sample "*"----"1" Barcode : identified by >
Company "1"----"1" ExternalApi : resort to >
Barcode "*"----"1" ExternalApi : generated by >
ClinicalChemistryTechnologist ----|> Employee
ClinicalChemistryTechnologist "*"----"1" ChemicalLaboratory : works in >
ClinicalChemistryTechnologist "1"----"*" ChemicalAnalysis : performs >
ClinicalChemistryTechnologist "1"----"*" ChemicalResult : register the >
SpecialistDoctor ----|> Employee
SpecialistDoctor "1"----"*" ChemicalResult : analyzes
SpecialistDoctor "1"----"*" MedicalReport: write the >
MedicalReport "1..*"----"*" Client : delivered to >
Company "1"-----"1" ExternalModule : resort to >
ExternalModule "1"----"*" MedicalReport : validates >
LaboratoryCoordinator ----|> Employee
LaboratoryCoordinator "1"----"*" MedicalReport : validates >
LaboratoryCoordinator "1"----"*" ChemicalAnalyses : validates >
LaboratoryCoordinator "1"----"*" ChemicalResult : validates >
Company "1"----"1" NhsApi : resort to >
NhsApi "1"----"*" Covid19Report : send the >
MedicalLabTechnician "1"----"*" Client : call >
Client "1"----"1..*" Sample : provides >
Client "*"----"1" SMS : receives >
Client "*"----"1" Email : receives >
ChemicalAnalyses "1"----"1" ChemicalResult : > generates

@enduml