@startuml
skinparam classAttributeIconSize 0

class CreateClinicalAnalysisLaboratoryUI{
}

class CreateClinicalAnalysisLaboratoryController{
  +createClinicalAnalysisLaboratory(name, address, phoneNumber , TIN,\n laboratoryId,selectedTestTypesList)
  +saveClinicalAnalysisLaboratory()
  +getTestType()
}

class Company{
+getLaboratory()
}


class ClinicalAnalysisLaboratory {
  -String laboratoryId
  +create (name, address, phoneNumber , TIN ,\nlaboratoryId,selectedTestTypesList)


}

class Laboratory {
  -String name
  -String address
  -int phoneNumber
  -int tin
  +create (name, address, phoneNumber , TIN ,\n laboratoryId,selectedTestTypesList)
  +validateClinicalAnalysisLaboratory(cal)
  +addClinicalAnalysisLaboratory(cal)
  +saveClinicalAnalysisLaboratory(cal)
}






CreateClinicalAnalysisLaboratoryUI ..> CreateClinicalAnalysisLaboratoryController
CreateClinicalAnalysisLaboratoryController ..> Company
CreateClinicalAnalysisLaboratoryController ...> Laboratory
Company "1" --> "1" Laboratory : uses
Laboratory  <|--  ClinicalAnalysisLaboratory


@enduml