@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Test{
-internalCode
-nhsCode
-description
}

class Company{
-name
-designation
-category
-address
-headquarters
}

class Laboratory {
  -name
  -address
  -phoneNumber
  -tin
}

class ClinicalAnalysisLaboratory {
  -laboratoryId
}

class TestType{
-designation
-collectingMethod
}

class ChemicalLaboratory{

}

class Administrator {

}

Company "1"---- "1..*" Laboratory : owns >
ClinicalAnalysisLaboratory ----|> Laboratory
ClinicalAnalysisLaboratory "1..*"----"*" Test : performs >
TestType "1"----"*" Test : is a >
Administrator "1"---"1..*"ClinicalAnalysisLaboratory : creates >
ChemicalLaboratory ----|> Laboratory



@enduml