@startuml
autonumber
actor "Administrator" as ADM

participant ":CreateClinicalAnalysisLaboratoryUI" as UI
participant ":CreateClinicalAnalysisLaboratoryController" as CTRL
participant ": Company" as Comp
participant "store: TestTypeStore" as TTS
participant "store: Laboratory" as LAB
participant "cal: ClinicalAnalysisLaboratory" as CAL

activate ADM
ADM -> UI : asks to create a new Clinical Analysis Laboratory
activate UI
UI --> ADM : requests data to create a new Clinical Analysis Laboratory \n (name, address, phoneNumber , TIN, laboratoryId)
deactivate UI

ADM -> UI : types requested data
activate UI

UI -> CTRL : lc=getTestType()
activate CTRL

CTRL -> TTS : lc=getTestType()
activate TTS
|||
deactivate TTS
deactivate CTRL

UI --> ADM : shows a TestType list and ask to choose the ones intended
deactivate UI

ADM -> UI : selects the TestTypes intended
activate UI

UI -> CTRL : createClinicalAnalysisLaboratory(name, address, phoneNumber , TIN, laboratoryId,selectedTestTypesList)
activate CTRL

CTRL -> Comp : store = getLaboratory()
activate Comp
|||
deactivate Comp

CTRL -> LAB: cal = createClinicalAnalysisLaboratory\n(name, address, phoneNumber , TIN, laboratoryId,selectedTestTypesList)
activate LAB
|||
LAB -> CAL**: create (name, address, phoneNumber , TIN ,\n laboratoryId,selectedTestTypesList)
deactivate LAB
CTRL -> LAB : validateClinicalAnalysisLaboratory(cal)
activate LAB
deactivate LAB
deactivate CTRL

UI --> ADM: shows all data and requests confirmation
deactivate CTRL
deactivate UI

ADM -> UI : confirms the data
activate UI
UI -> CTRL : saveClinicalAnalysisLaboratory()
activate CTRL

CTRL -> LAB : saveClinicalAnalysisLaboratory(cal)
activate LAB

LAB -> LAB: validateClinicalAnalysisLaboratory(cal)
activate LAB
deactivate LAB
LAB -> LAB: addClinicalAnalysisLaboratory(cal)
activate LAB
deactivate LAB
deactivate LAB

UI --> ADM : informs operation success
deactivate CTRL
deactivate UI

deactivate ADM

@enduml