@startuml
autonumber
actor "Administrator" as Adm

activate Adm
Adm -> ":System" : asks to create a new Clinical Analysis Laboratory
activate ":System"
":System" --> Adm : requests data (name, address, phoneNumber , TIN, laboratoryId )

deactivate ":System"

Adm -> ":System" : types requested data
activate ":System"
":System" --> Adm : shows a TestType list and ask to choose the ones intended
deactivate ":System"
loop * while the user selects the TestTypes intended
Adm -> ":System" : selects the TestTypes intended
activate ":System"
end
":System" --> Adm : shows all data and requests confirmation
deactivate ":System"


Adm -> ":System" : confirms the data
activate ":System"
":System" --> Adm : informs the operation success
deactivate ":System"

deactivate Adm

@enduml