@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Test{
-internalCode
-nhsCode
-description
}

class Company{
-name
-designation
-category
-address
-headquarters
}

class Laboratory {
  -name
  -address
  -phoneNumber
  -tin
}

class ClinicalAnalysisLaboratory {
  -laboratoryId
}

class Employee {
  -name
  -address
  -phoneNumber
  -email
  -employeeId
  -organizationRole
  -socCode
}


class Administrator {

}

Company "1"---- "1..*" Laboratory : owns >
ClinicalAnalysisLaboratory ----|> Laboratory
ClinicalAnalysisLaboratory "1..*"----"*" Test : performs >
Administrator "1"---"1..*"ClinicalAnalysisLaboratory : creates >
Administrator --|> Employee



@enduml