@startuml
skinparam classAttributeIconSize 0

class CreateClinicalAnalysisLaboratoryUI{
}

class CreateClinicalAnalysisLaboratoryController{
  +createClinicalAnalysisLaboratory(calDTO))
  +getTestTypeList()
  +saveClinicalAnalysisLaboratory(cal)
}

class Company{
  +getClinicalAnalysisLaboratoryStore()
}


class ClinicalAnalysisLaboratory {
  -String laboratoryId
  +create (calDTO))


}

class Laboratory {
  -String name
  -String address
  -int phoneNumber
  -int tin

}

class TestTypeStore{
+getTestTypeList()
}

class ClinicalAnalysisLaboratoryStore{
  +getClinicalAnalysisLaboratory()
  +createClinicalAnalysisLaboratory(calDTO)
  +validateClinicalAnalysisLaboratory(cal)
  +addClinicalAnalysisLaboratory(cal)
}

class ClinicalAnalysisLaboratoryMapper {
   +toDTO(listTestType)
}

class TestTypeMapper {
   +toDTO(listTestType)
}


class ClinicalAnalysisLaboratoryDTO {
  -String name
  -String address
  -int phoneNumber
  -int tin
  -String laboratoryId
  +create (name, address, phoneNumber , TIN ,\nlaboratoryId,selectedTestTypesList)
}

class TestType{
  -String code
  -String description
  -String collectingMethod
  -List<ParameterCategories> listOfParameterCategories
  +TestType(code,description,collectingMethod,listOfParameterCategories)
}

class TestTypeDTO{
  -String code
  -String description
  -String collectingMethod
  -List<ParameterCategories> listOfParameterCategories
  +TestType(code,description,collectingMethod,listOfParameterCategories)
}






CreateClinicalAnalysisLaboratoryUI ..> CreateClinicalAnalysisLaboratoryController
CreateClinicalAnalysisLaboratoryUI ..> ClinicalAnalysisLaboratoryDTO
CreateClinicalAnalysisLaboratoryController ..> ClinicalAnalysisLaboratoryDTO
CreateClinicalAnalysisLaboratoryController ..> Company
CreateClinicalAnalysisLaboratoryController ...> TestTypeStore
CreateClinicalAnalysisLaboratoryController ..> ClinicalAnalysisLaboratoryMapper
CreateClinicalAnalysisLaboratoryController ..> ClinicalAnalysisLaboratoryStore
CreateClinicalAnalysisLaboratoryController ..> TestTypeMapper
ClinicalAnalysisLaboratoryStore"1" --> "1" ClinicalAnalysisLaboratory : conducts
Laboratory  <|- ClinicalAnalysisLaboratory
ClinicalAnalysisLaboratoryMapper ..> ClinicalAnalysisLaboratoryDTO
ClinicalAnalysisLaboratoryMapper ...> ClinicalAnalysisLaboratory
Company "1" --> "1" ClinicalAnalysisLaboratoryStore : uses
TestTypeStore "1" --> "*" TestType : conducts
TestTypeMapper --> TestTypeDTO
@enduml