@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Receptionist {

}

class Client {
 - Name
 - Email
 - Phone Number
 - Sex
 - TIF
 - Birth Date
 - NHS Number
 - Citizen Card Number

}

class Doctor {

}

class Administrator{

}



class LabOrder {

}

class Category {

}

class TestType {
- Blood
- Covid 19
}

class Sample {
- Barcode
}

class Report {
-Diagnosis

}

class Test {
- internal code
- NHS code
- description
- date samples collected
- time samples collected
- date chemical analysis
- time chemical analysis
- date diagnosis made
- time diagnosis made
- date of validation by laboratory coordinator
- time of validation by laboratory coordinator
}
class Parameter {


}

class Company {

}

class ChemicalLaboratory{

}

class MedicalLabTechnician {

}

class ChemicalAnalysis {

}

class ClinicalAnalysisLaboratory{

}

class application{

}


Client "*" -- "1" Receptionist: registers the <
LabOrder "*" -- "1" TestType: contain the >
Client "1" -- "*" LabOrder: has a >
Report "1" -- "*" Doctor: write a <
Receptionist "*" -- "*" Test: registers the >
Test "*" -- "1" TestType: is of >
Parameter "*" -- "1" Category: present under >
Category "*" -- "1" Administrator: created by >
Company "1" -- "*" Test: performs >
Sample "*" -- "1" ChemicalLaboratory: sent to >
Company "1" -- "*" TestType: conducts >
MedicalLabTechnician "1" -- "*" Client: calls >
ChemicalLaboratory "1" -- "*" ChemicalAnalysis: performs the >
MedicalLabTechnician "1" -- "*" Sample: records the >
Company "1" -- "*" ClinicalAnalysisLaboratory: owns >
ChemicalLaboratory "*" -- "1" Company: owns <
LabOrder "*" -- "*" Parameter: contain the <
MedicalLabTechnician "1" -- "*" Test: registers the >
MedicalLabTechnician "1" -- "*" Sample: collect the >
Doctor "1" -- "*" ChemicalAnalysis: analyzes the results of >
Report "1" -- "*" Client: delivered to >


@enduml