@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {

}

class Receptionist {

}

class Client {
 - Name
 - Email
 - Phone Number
 - Sex
 - TIF
 - Birth Date
 - NHS Number
 - Citizen Card Number

}

class Doctor {

}

class Administrator{

}
class LabCoordinator{
}


class LabOrder {

}

class Category {

}

class TestType {
- Blood
- Covid 19
}

class Sample {
- Barcode
}

class ChemicalLaboratory{

}

class Report {
-Diagnosis

}

class Test {
- internal code
- NHS code
- description
- date samples collected
- time samples collected
- date chemical analysis
- time chemical analysis
- date diagnosis made
- time diagnosis made
- date of validation
- time of validation
}
class Parameter {


}


class MedicalLabTechnician {

}

class ChemicalAnalysis {

}

class ClinicalAnalysisLaboratory{

}

ChemicalLaboratory "*" --- "1" Company: owns <
Company "1" -- "*" ClinicalAnalysisLaboratory: owns >
Company "1" -- "*" Test: performs >
Company "1" -- "*" TestType: conducts >
Test "*" --- "1" TestType: is of >
Receptionist "*" -- "*" Test: registers the >
LabOrder "*" ------ "1" TestType: contain the >
MedicalLabTechnician "1" -- "*" Test: registers the >
Client "1" -- "*" LabOrder: has a >
LabOrder "*" -- "*" Parameter: contain the >
Client "*" -- "1" Receptionist: registers the <
MedicalLabTechnician "1" --- "*" Client: calls >
Client "*" -- "1" Report: delivered to <
Report "1" -- "*" Doctor: write a <
Report "*" -- "1" API: verified by >
Report "1" -- "1" LabCoordinator : verified by >
Parameter "*" -- "1" Category: present under >
Category "*" -- "1" Administrator: created by >
Doctor "1" -- "*" ChemicalAnalysis: analyzes the results of >
ChemicalLaboratory "1" -- "*" ChemicalAnalysis: performs the >
MedicalLabTechnician "1" -- "*" Sample: records the >
MedicalLabTechnician "1" ---- "*" Sample: collect the >
Sample "*" --- "1" ChemicalLaboratory: sent to >


@enduml