@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Client" as CLIENT
participant ": System" as SYSTEM

CLIENT->SYSTEM : starts the update of data
activate CLIENT
activate SYSTEM
loop while the client wants to update his data
SYSTEM-->CLIENT : show the personal data of the client
deactivate SYSTEM
CLIENT->SYSTEM : type the new data
activate SYSTEM
SYSTEM-->CLIENT : show the new data an ask for confirmation
deactivate SYSTEM
CLIENT->SYSTEM: confirm data
activate SYSTEM
SYSTEM-->CLIENT : show the operation success
deactivate SYSTEM
deactivate CLIENT
end loop


@enduml