@startuml
autonumber
actor "Administrator" as Adm

activate Adm
Adm -> ":System" : Initiates the test type creation
activate ":System"
":System" --> Adm : Request the necessary data to create a\n type of test (code,description,collecting method)
deactivate ":System"

Adm -> ":System" : Introduce the requested data
activate ":System"
":System" --> Adm : Show the existing parameter categories and ask\n to select one or more
deactivate ":System"

Adm -> ":System" : Select the desired parameter categories
activate ":System"
":System" --> Adm : Presents all data and requests confirmation
deactivate ":System"

Adm -> ":System" : Confirms the data
activate ":System"
":System" --> Adm : Informs operation success
deactivate ":System"

deactivate Adm

@enduml