@startuml
hide methods
'left to right direction
skinparam classAttributeIconSize 0

class Company{
-designation
}


class Administrator{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class TestType{
-code
-description
-collectingMethod
}


class ParameterCategory{
-name
-code
}


Company "1"--"1..*" Administrator : has >
Company "1"--"*" TestType : conducts >
Administrator "*"--"*" TestType : specifies the >
ParameterCategory "*"--"*" TestType : has a set of <

@enduml