@startuml
autonumber
'hide footbox
actor "Administrator" as Adm

participant ": CreateTestTypeUI" as UI
participant ": CreateTestTypeController" as CTRL
participant ": Company" as Comp
participant "store: TestTypeStore" as str
participant ": ParameterCategoryStore" as PC
participant "t: TestType" as TT

activate Adm
Adm -> UI : Initiates the test type creation
activate UI
UI --> Adm : Request the necessary data to create a\n type of test (code,description,collecting method)
deactivate UI

Adm -> UI : Introduce the requested data
activate UI
UI -> CTRL : lc=getParameterCategories()
activate CTRL
CTRL -> Comp : store = getParameterCategoryStore()
activate Comp
deactivate Comp
CTRL -> PC : lc=getParameterCategories()
activate PC
deactivate PC
deactivate CTRL
UI --> Adm : Show the existing parameter categories\n and ask to select one or more
deactivate UI

Adm -> UI : Select the desired parameter category
activate UI
UI -> CTRL : createTestType(code,description,collectingMethod,listOfParameterCategories)
activate CTRL
CTRL -> Comp : store = getTestTypeStore()
activate Comp
deactivate Comp
loop
CTRL -> PC : listOfParameterCategories=getParameterCategorybyCode()
activate PC
deactivate PC
end
CTRL -> str : testType = createTestType(code,description,collectingMethod,listOfParameterCategories)
activate str
str -> TT** : create(code,description,collectingMethod,listOfParameterCategories)
deactivate str
str-> str : validateTestType(testType)
activate str
deactivate str
CTRL --> UI: result
deactivate CTRL
UI --> Adm : Presents all data and requests confirmation
deactivate UI

Adm -> UI: Confirms the data
activate UI
UI -> CTRL: saveTestType()
activate CTRL
CTRL -> str : saveTestType(testType)
activate str
str -> str : validateTestType(testType)
activate str
deactivate str
str ->str : addTestType(testType)
activate str
deactivate str
deactivate str
CTRL --> UI: result
deactivate CTRL
UI --> Adm : Informs operation success
deactivate UI

deactivate Adm




@enduml