@startuml
skinparam classAttributeIconSize 0

class Company{
-String name
-String designation
-category
-address
-headquarters
}

class CreateTestTypeUI{
}

class CreateTestTypeController{
}

class TestType{
}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class Laboratory{
-String name
-String address
-int phoneNumber
-int TIN
}

CreateTestTypeUI ..> CreateTestTypeController
CreateTestTypeController ..> Company
Company --> TestType
ClinicalAnalysisLaboratory ---|> Laboratory



@enduml