@startuml
skinparam classAttributeIconSize 0

class Company{
-String name
-String designation
-category
-address
-headquarters
}

class CreateTestTypeUI{
}

class CreateTestTypeController{
}

class TestType{
}

class Category{
-name
}

CreateTestTypeUI ..> CreateTestTypeController
CreateTestTypeController ..> Company
Company --> TestType


@enduml