8@startuml
autonumber
actor "Client" as OE

activate OE
OE -> ":System" : asks to view the results of his tests
activate ":System"
":System" --> OE : shows the test list and asks to choose one
deactivate ":System"

OE -> ":System" : selects a test
activate ":System"
":System" --> OE : shows requested data
deactivate ":System"

deactivate OE

@enduml