@startuml
'https://plantuml.com/sequence-diagram
autonumber

participant ":{???}Controller" as CTRL
participant "APP" as APP
participant "app: APP" as app
participant "session: UserSession" as session
participant ""



@enduml