@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor "Administrator" as Adm
actor "Recepcionist" as Recp
actor "Med lab technician" as MedLab
actor "Clinical chemistry technologist" as ClinTec
actor "Specialist Doctor" as Doc
actor "Laboratory Coordinator" as LabCod
actor "Time" as Time


rectangle ManyLabs{

usecase "UC03: Register a new client" as UC03
usecase "UC04: Register a test to be performed to a registered client" as UC04
usecase "UC12: Record the samples collected in the scope of a given test" as UC12
usecase "UC13: Associate a barcode with each sample" as UC13
usecase "UC15: Register the tests performed locally" as UC15
usecase "UC16: Record the result of chemistry analysis" as UC16
usecase "UC14 : Associate the samples to the client/test" as UC14
usecase "UC09: Specify a new type of test and its collecting methods" as UC09
usecase "UC10: Specify a new test parameter and categorize it" as UC10
usecase "UC11: Specify a new parameter category" as UC11
usecase "UC06: Write a report" as UC06
usecase "UC01: Validation of test performed" as UC01
usecase "UC02: Access the company response efficiency" as UC02
usecase "UC05: Access a internal process of a client" as UC05
usecase "UC17: Send daily Covid-19 data" as UC17
usecase "UC07: Register a new employee" as UC07
usecase "UC08: Register a new clinical analysis laboratory stating which kind of test(s) it operates." as UC08

}

Recp -- UC03
Recp -- UC04
MedLab -- UC12
MedLab -- UC13
MedLab -- UC15
MedLab -- UC14
ClinTec -- UC16
UC07 --- Adm
UC08 --- Adm
UC09 --- Adm
UC11 --- Adm
UC10 --- Adm
UC05 --- Doc
UC06 --- Doc
UC01 --- LabCod
UC02 --- LabCod
Time -- UC17







@enduml