@startuml
'https://plantuml.com/sequence-diagram
'hide footbox
autonumber

participant ": TestParameterMapper" as Mapper
participant "testParametersList:\n List<TestParameter>" as lTP
participant "testParametersListDto:\n List<TestParameterDto>" as lTPDto
participant "tp:\n TestParameter" as TP
participant "dto:\n TestParameterDto" as TPDto

-> Mapper : toDto(testParametersList)
activate Mapper
Mapper --> lTPDto** : create()
loop for each object in testParametersList
Mapper -> lTP : testParameterAux = get(i)
activate lTP
deactivate lTP
Mapper -> TP: parameterName = getParameterName()
activate TP
deactivate TP
Mapper -> TP: testParameterResult = getParameterResult()
activate TP
deactivate TP
Mapper -> TP: testParameterMetric= getParameterMetric()
activate TP
deactivate TP
Mapper -> TP: testParameterMinRefValue= getParameterMinRefValue()
activate TP
deactivate TP
Mapper -> TP: testParameterMaxRefValue= getParameterMaxRefValue()
activate TP
deactivate TP
Mapper --> TPDto** : create(parameterName,testParameterResult,testParameterMetric,testParameterMinRefValue,testParameterMaxRefValue)
Mapper -> lTPDto : add(dto)
activate lTPDto
deactivate lTPDto
end
<-- Mapper : testParametersListDto



@enduml