@startuml
'https://plantuml.com/sequence-diagram
'hide footbox
autonumber

participant ": testMapper" as MAPPER
participant "testHasSamplesAnalyzedList: \nList<Test>" as LTestSA
participant "testHasSamplesAnalyzedListDto: \nList<TestDto>" as LTestSADTO
participant "test : Test" as TEST
participant "testDto : TestDto" as TESTDTO

-> MAPPER : toDto(testHasSamplesAnalyzedList)
activate MAPPER
MAPPER --> LTestSADTO** : create()
loop for each object in testHasSamplesAnalyzedList
MAPPER -> LTestSA : testAux = get(i)
activate LTestSA
deactivate LTestSA
MAPPER -> TEST : testDescription = getDescription()
activate TEST
deactivate TEST
MAPPER -> TEST : testInternalCode = getInternalCode()
activate TEST
deactivate TEST
MAPPER --> TESTDTO** : create(testDescription, testInternalCode)
MAPPER -> LTestSADTO : add(testDto)
activate LTestSADTO
deactivate LTestSADTO
end
deactivate MAPPER
<-- MAPPER : listTestWaitingForResultDto

@enduml