@startuml

class Company{
-String designation

}

class CreateMedicalReportUI{

}

class CreateMedicalReporController{

}

CreateMedicalReportUI ..> CreateMedicalReporController
CreateMedicalReporController ..> Company

@enduml