@startuml
autonumber
'hide footbox
actor "Specialist Doctor" as Doctor

participant ": CreateMedicalReportUI" as UI
participant ": CreateMedicalReportController" as CTRL
participant ": Company" as Comp

activate Doctor
Doctor -> UI : Initiates the process of elaborate a medical report.
activate UI
UI -> CTRL
activate CTRL
CTRL -> Comp :
activate Comp
deactivate Comp
deactivate CTRL
UI --> Doctor : Shows the tests that are waiting for the \n medical report and asks to select one.
deactivate UI

Doctor -> UI :  Select the desired test.
activate UI
UI --> Doctor : Shows the parameter results and request the medical report.
deactivate UI

Doctor-> UI : Introduces the medical report.
activate UI


UI --> Doctor : Displays the data and requests confirmation.
deactivate UI

Doctor-> UI : Confirms the data.
activate UI
UI --> Doctor : Informs operation success.
deactivate UI

deactivate Doctor



@enduml