@startuml
autonumber
'hide footbox
actor "Specialist Doctor" as Doctor

participant ": CreateMedicalReportUI" as UI
participant ": CreateMedicalReportController" as CTRL
participant ": Company" as Comp
participant "testStore:\nTestStore" as TS
participant ": TestMapper" as tMAPPER
participant "testHasSamplesAnalyzedList: \nList<Test>" as List
participant "testHasSamplesAnalyzedListDto :\nList<TestDto> " as TDto
participant "test:Test" as TEST
participant "testDto: TestDto" as TestDtoc
participant ": TestParameterMapper" as tpMAPPER
participant "testParametersList:\n List<TestParameter>" as lTP
participant "testParametersListDto:\n List<TestParameterDto>" as lTPDto
participant "tp:\n TestParameter" as TP
participant "dto:\n TestParameterDto" as TPDto
participant "md: MedicalReport" as REPORT

activate Doctor
Doctor -> UI : Initiates the process of elaborate a medical report.
activate UI
UI -> CTRL : testHasSamplesAnalyzedListDto = getTestHasSamplesAnalyzedList()
activate CTRL
CTRL -> Comp : testStore = getTestStore()
activate Comp
deactivate Comp
CTRL -> TS : testHasSamplesAnalyzedList = getTestHasSamplesAnalyzedList()
activate TS
deactivate TS
CTRL -> tMAPPER : toDto(testHasSamplesAnalyzedList)
activate tMAPPER
ref over tMAPPER
SD_TestMapper_toDto_List
end ref
tMAPPER --> CTRL : testHasSamplesAnalyzedListDto
deactivate tMAPPER
CTRL --> UI : testHasSamplesAnalyzedListDto
deactivate CTRL
UI --> Doctor : Shows the tests that are waiting for the \n medical report and asks to select one.
deactivate UI

Doctor -> UI :  Select the desired test.
activate UI
UI -> CTRL : testParametersListDto = getTestParameterList()
activate CTRL
CTRL -> TS : test = getTestByInternalCode(code)
activate TS
deactivate TS
CTRL -> TEST : testParametersList= getTestParametersList()
activate TEST
deactivate TEST
CTRL -> tpMAPPER : toDto(testParametersList)
activate tpMAPPER
ref over tpMAPPER
SD_TestParameterMapper_toDto_List
end ref
tpMAPPER --> CTRL : testParametersListDto
deactivate tpMAPPER
CTRL --> UI : testParametersListDto
deactivate CTRL
UI --> Doctor : Shows the parameter results and request the medical report.
deactivate UI

Doctor-> UI : Introduces the medical report.
activate UI

UI --> Doctor : Displays the data and requests confirmation.
deactivate UI

Doctor-> UI : Confirms the data.
activate UI
UI -> CTRL: createMedicalReport()
activate CTRL
CTRL -> TEST : md = createMedicalReport(diagnosis)
activate TEST
TEST --> REPORT** : create(diagnosis)
deactivate TEST
CTRL --> UI : result
deactivate CTRL
UI --> Doctor : Informs operation success.
deactivate UI

deactivate Doctor



@enduml