@startuml

package UI{
class CreateMedicalReportUI{
}
}

package Controller{
class CreateMedicalReporController{
+getTestHasSamplesAnalyzedList()
+getTestParameterList()
+createMedicalReport()
}
}

package Model{
class Company{
-String designation
+getTestStore()
}

class Test{
+getParametersResulList()
+createMedicalReport(report)
}

class MedicalReport{
-String diagnosis
-Date createdAt
+ MedicalReport(diagnosis)
}

class TestParameter{
}
}

package Store{
class TestStore{
+getTestHasSamplesAnalyzedList()
+getTestByInternalCode(code)
}
}

package Mappers{
class TestMapper{
}

class TestParameterMapper{
}
}

package DTO{
class TestDto{
}

class TestParameterDto{
}
}


CreateMedicalReportUI ..> CreateMedicalReporController
CreateMedicalReportUI ..> TestDto
CreateMedicalReportUI ..> TestParameterDto
CreateMedicalReporController ..> Company
CreateMedicalReporController ..> TestMapper
CreateMedicalReporController ..> TestParameterMapper
TestParameterMapper ..> TestParameterDto
TestParameterMapper ..> TestParameter
TestMapper ..> TestDto
TestMapper ..> Test
Company --> Test
Test "*"--"1" MedicalReport : request >
Company"1"--> "1" TestStore : uses

@enduml