@startuml
'https://plantuml.com/class-diagram

class ExternalModule

package ui{
class RecordSampleUI
}
package controller{
class RecordSampleController
}
package domain{

package model{
class Company
class Test
class Sample
}
package store{
class TestStore
class SampleStore
}
package mappers{

class TestMapper

package dto{
class TestDTO

}
}
}

class Test{
-nhsCode
-testCode


}

class Company{
-designation
-testStore
-sampleStore
+getSampleStore()
+getTestStore()
}

class RecordSampleController{
+getListTestDto()
+createSample()
}

class TestStore{
+getListTestWaitingForSamples()
}

class SampleStore{
+createSample()
}

class Test{
+generateDateAndTimeForSamplesCollected()
+getNhsCode()
+getTestCode()
}

class TestMapper {
+toDto(listWaitingForSample)
}

class TestDTO {
-nhsCodeDto
-testCodeDto
+getNhsCodeDto()
+getTestCodeDto()
}

class Sample {
-barcode
+generateBarcode()
+AssociateBarcodeWithSample(barcode)

}

RecordSampleUI..>RecordSampleController
RecordSampleController..>Company
Company"1"---->"1"SampleStore : uses
Company"1"--->"1"TestStore : uses
SampleStore "1" --> "*"Sample : knows
TestStore "1"---->"*"Test : knows
Test --* Sample
Company .>ExternalModule
TestDTO.>TestMapper
TestMapper..>Test



@enduml