@startuml
autonumber
actor "Med Lab Technician" as MEDLAB
participant ": RecordSampleUI" as UI
participant ": RecordeSampleController" as CONTROLLER
participant ": Company" as COMPANY
participant "chemicalLab : ChemicalLaboratory" as LAB
participant "store : \nTestStore" as TESTSTORE
participant "store : \nSampleStore" as SAMPLESTORE
participant "test : Test" as TEST
participant "listTestWaitingForSample :\nList<Test>" as TESTLIST
participant ": ExternalModuleBarcode" as INTERFACE
participant ": TestMapper" as MAPPER
participant "testDto :\nTestDto" as TESTDTO
participant "listTestWaitingForSamplesDto :\nList<TestDto>" as TESTDTOLIST









MEDLAB -> UI : start recording samples for a test
activate MEDLAB
activate UI
UI -> CONTROLLER : listTestWaitingForSampleDto = getListTestDto()
activate CONTROLLER
CONTROLLER -> COMPANY : store = getTestStore()
activate COMPANY
deactivate COMPANY
CONTROLLER -> TESTSTORE : listTestWaitingForResult = getListTestWantingForSamples()
activate TESTSTORE
deactivate TESTSTORE
CONTROLLER -> MAPPER : toDto(listTestWantingForSample)
activate MAPPER
ref over MAPPER
SD_TestMapper
end ref

MAPPER-->CONTROLLER : listTestWaitingForSampleDto
deactivate MAPPER
CONTROLLER --> UI : listTestWaitingForSampleDto




deactivate CONTROLLER

UI --> MEDLAB : shows the tests that are waiting \n to be associated with a sample
deactivate UI

MEDLAB -> UI : select a test
activate UI
UI->CONTROLLER : getTestByInternalCode(testDto)
activate CONTROLLER
CONTROLLER->TESTSTORE : test = getTestByInternalCode(code)
activate TESTSTORE
deactivate TESTSTORE
deactivate CONTROLLER
UI --> MEDLAB : asks the number of samples that will \n be recorded for the selected test
deactivate UI
MEDLAB ->UI : enter the number of samples that \nwill be associated with the test
activate UI
loop for the number of samples entered
UI->CONTROLLER : generateBarcode()
activate CONTROLLER
CONTROLLER->INTERFACE : generateBarcode()
activate INTERFACE
INTERFACE-> "barcode : BarcodeDomain"** : create()
INTERFACE-->CONTROLLER : barcode
CONTROLLER-->UI : barcode
deactivate INTERFACE


deactivate CONTROLLER

UI --> MEDLAB : shows the data and request confirmation
deactivate UI
MEDLAB -> UI : confirms the data
activate UI
UI->CONTROLLER : associateBarcodeWithSample(barcode)
activate CONTROLLER
CONTROLLER->COMPANY : chemicalLab = getChemicalLaboratory()
activate COMPANY
deactivate COMPANY
CONTROLLER-> LAB : store = getSampleStore()
activate LAB
deactivate LAB


CONTROLLER->SAMPLESTORE : createSample(barcode)
activate SAMPLESTORE
SAMPLESTORE->"sample : Sample"** : create()
deactivate SAMPLESTORE
CONTROLLER->TESTSTORE : associateSamplesWithTest(test, sample)
activate TESTSTORE
TESTSTORE->TEST : addSample(sample)
activate TEST

deactivate TESTSTORE
opt listSamplesAssociatedWithTest = number of samples entered by the user

TEST->TEST : changeStateForSamplesCollected()
activate TEST
deactivate TEST
TEST->TEST : generateDataAndTimeForSamplesCollected()
activate TEST
deactivate TEST

end opt
deactivate TEST

end loop


UI --> MEDLAB : informs the operation success
deactivate UI
@enduml

