@startuml
autonumber
actor "Med Lab Technician" as MEDLAB
participant ": RecordSampleUI" as UI
participant ": RecordeSampleController" as CONTROLLER
participant ": Company" as COMPANY
participant ": TestStore" as TESTSTORE
participant ": Test" as TEST
participant ": listTestWaitingForSample" as TESTLIST
participant ": TestMapper" as MAPPER
participant ": TestDto" as TESTDTO
participant ": ListTestWaitingForSamplesDto" as TESTDTOLIST
participant ": Sample" as SAMPLE
participant ": SampleStore" as SAMPLESTORE
participant ": ExternalModule" as EXTERNALMODULE







MEDLAB -> UI : start recording samples for a test
activate MEDLAB
activate UI
UI -> CONTROLLER : listTestWaitingForSampleDto = getListTestDto()
activate CONTROLLER
CONTROLLER -> COMPANY : store = getTestStore()
CONTROLLER -> TESTSTORE : listTestWaitingForResult = getListTestWantingForSamples()
activate TESTSTORE
deactivate TESTSTORE
CONTROLLER -> MAPPER : toDto(listTestWantingForSample)
activate MAPPER
ref over MAPPER
SD_TestMapper
end ref

MAPPER-->CONTROLLER : listTestWaitingForSampleDto
deactivate MAPPER
CONTROLLER --> UI : listTestWaitingForSampleDto




deactivate CONTROLLER

UI --> MEDLAB : shows the tests that are waiting \n to be associated with a sample
deactivate UI
MEDLAB -> UI : select a test
activate UI
UI --> MEDLAB : asks the number of samples that will \n be recorded for the selected test
deactivate UI
MEDLAB ->UI : enter the number of samples that \nwill be associated with the test

activate UI
UI --> MEDLAB : shows the data and request confirmation
deactivate UI
MEDLAB -> UI : confirms the data
activate UI
UI --> MEDLAB : informs the operation success
deactivate UI
@enduml

