@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company{
-designation
}

class Laboratory{
-name
-address
-phoneNumber
-tin
}

class ClinicalAnalysisLaboratory{
-laboratoryId
}

class ChemicalLaboratory{
}


class Employee{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}


class Client{
 - name
 - email
 - phoneNumber
 - sex
 - tin
 - birthDate
 - nhsNumber
 - citizenCardNumber
}

class Test{
-internalCode
-nhsCode
-description
-dateOfSampleCollected
-timeOfSampleCollected
-dateOfSampleAnalysis
-timeOfSampleAnalysis
-state
}

class TestParameter{
}

class TestParameterResult{
-value
-metric
}

class Sample{

}

class LabCoordinatorValidation {
-dateAndTime
}

class TestType{
-code
-description
-collectingMethod
}

class Parameter{
-code
-designation
-description
}


class ParameterCategory{
-name
-code
}

class ChemicalAnalysis{
-dateAndTime
}

class LabOrder{
}

class Barcode{
-code
}

class ExternalApi{
}

class SpecialistDoctor{
-doctorIndexNumber
}

class MedicalReport{
-diagnosis
-dateAndTime
}

class ExternalModule{

}

class ReferenceValue{
-lowerLimitValue
-upperLimitValue
}

class NhsApi{
}

class Covid19Report{
}

class EmailNotification{
-message
}

class SMSNotification{
-message
}

class EmailLogin{
-password
}


class OrganizationRole{
}

Company "1"---------------"1..*" Laboratory : has >
Company "1"---"1..*" Employee : employ >
Company "1"---"1..*" OrganizationRole : comprehends >
Company "1"---"1..*" Parameter : capable of analyzing >
Company "1"---"1..*" ParameterCategory : adopts >
Company "1"---"1..*" Test : performs >
Company "1"--------------"1..*" TestType : conducts >
Company "1"---"1" ExternalApi : resort to >
Company "1"---"1" ExternalModule : resort to >
Company "1"---"1" NhsApi : resort to >

Employee "*"---"1" OrganizationRole : play >

ClinicalAnalysisLaboratory ---|> Laboratory
ClinicalAnalysisLaboratory "1..*"---"1..*" Test : perform >
ClinicalAnalysisLaboratory "*"---"1" Employee : registered by >

ChemicalLaboratory ---|> Laboratory
ChemicalLaboratory "1"---"*" ChemicalAnalysis : perform >

Test "*"---"1" Employee : registered by >
Test "1..*"---"1" Client : associated a >
Test "1..*"---"1..*" Sample : request  >
Test "*"---"1..*" Parameter : measure >
Test "1..*"---"1" TestType : is of >
Test "1..*" ---"1" ChemicalAnalysis : request >
Test "1..*" ---"1" MedicalReport : request >
Test "*" --- "1" LabCoordinatorValidation : request >
(Test,Parameter) . TestParameter

TestParameter "1" --- "0..1" TestParameterResult : contains >
TestParameter "1" --- "1" Parameter : associated with >

LabCoordinatorValidation "*"--"1" Employee : made by >

Parameter "*"---"1" ParameterCategory : presented under >
Parameter "1..*" ---"1" ChemicalAnalysis : analyzed by >
Parameter "*" --- "1" Employee : specified by >

ParameterCategory "*"--"1" Employee : specified by >

TestType "*"---"1..*" ParameterCategory : has a set of >
TestType "*"---"1" Employee : specified by >
TestType "*" -- "1" ExternalModule : resort to >

TestParameterResult "1..*"---"1" LabCoordinatorValidation : validated by >
TestParameterResult "1..*"---"1" Employee: registered by >
TestParameterResult "1..*"---"1" SpecialistDoctor : analyzed by >
TestParameterResult "1" --- "1" ReferenceValue : records >

Sample "*"---"1" ChemicalLaboratory : sent to >
Sample "1"---"1" Barcode : identified by >
Sample "*"---"1" Employee : registered by >

Barcode "*"---"1" ExternalApi : generated by >

Client "1"---"1..*" LabOrder : has a >
Client "1"---"1..*" Sample : provides >
Client "*"---"1..*" SMSNotification : receives >
Client "*"---"1..*" EmailNotification : receives >
Client "*"---"1" EmailLogin : receives >
Client "*"---"1" Employee : registered by >

LabOrder "1"---------"1" Test : prescribe >
LabOrder "1..*"---"1" TestType : contains the >
LabOrder "*"---"1..*" Parameter : contains the >

ChemicalAnalysis "1" --- "1..*" Sample : analyzes >
ChemicalAnalysis "1"---"1..*" TestParameterResult: generates >

SpecialistDoctor ---|> Employee

MedicalReport "1..*"---"1" Client : sent to >
MedicalReport "*"---"1" LabCoordinatorValidation : validated by >
MedicalReport "*"---"1" SpecialistDoctor : written by >

ExternalModule "1"---"*" MedicalReport : validates >
ExternalModule "1"---"1..*" ReferenceValue : provides >


NhsApi "1"---"*" Covid19Report : send the >

EmailNotification "1"---"1" Test : associated to >

SMSNotification "1"---"1" Test : associated to >

@enduml