@startuml
autonumber
actor "Client" as OE

activate OE
OE -> ":System" : asks to view the results of his tests
activate ":System"
":System" --> OE : shows the test list and asks to choose one
deactivate ":System"

loop
OE -> ":System" : selects a test
activate ":System"
":System" --> OE : shows all data
deactivate ":System"
end

deactivate OE

@enduml