@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant ":RegisterTestController" as CTRL
participant ":TestTypeMapper" as MapperTT

CTRL -> MapperTT :toDTO(listTestType)
activate MapperTT
MapperTT --> "TestTypeListDTO:List<TestTypeDTO>"** :create()
loop for each object in TestTypeList
MapperTT -> "listTestType:List<TestType>" : obj= get(i)
activate "listTestType:List<TestType>"
deactivate "listTestType:List<TestType>"
MapperTT -> MapperTT : objDTO = toDTO(obj)
activate MapperTT
MapperTT -> "objDTO : TestTypeDTO"** : create()
deactivate MapperTT
MapperTT -> "TestTypeListDTO:List<TestTypeDTO>" : add(objDTO)
activate "TestTypeListDTO:List<TestTypeDTO>"
deactivate "TestTypeListDTO:List<TestTypeDTO>"
end
MapperTT --> CTRL : TestTypeListDTO
@enduml