@startuml
skinparam classAttributeIconSize 0

class TestTypeStore{

}

class TestType{

}

class TestTypeMapper{

}

class TestTypeDTO{

}

class ParameterCategoryStore {

}

class ParameterCategory {

}

class ParameterCategoryMapper{

}

class ParameterCategoryDTO{

}

class ClientStore{

}

class Client{

}

class ClientMapper{

}

class ClientDto{

}

class Test{

}

class TestStore{

}

class ParameterStore {

}

class Parameter {

}

class ParameterMapper{

}

class ParameterDTO{

}

class Company {
  -String name
  -String VatNumber
  -String website
  -String phone
  -String email
  +Organization(name, VatNumber, webSite, phone, email, postalAddress, manager)
  +createTask(ref,designation,informalDesc,technicalDesc,duration,cost,cat)
  +saveTask(task)
  -addTask(task)
  -validateTask(task)
}

class RegisterTestController {

}

class RegisterTestUI {

}

RegisterTestUI ..> RegisterTestController
RegisterTestController ..> Parameter
RegisterTestController ..> ParameterStore
RegisterTestController ..> Company
RegisterTestController ..> TestTypeStore
RegisterTestController ..> TestType
ParameterStore "*" -> "1" Parameter : classified in
Platform "1" --> "*" Parameter : defines
Company "1" --> "*" ParameterStore : owns


@enduml