@startuml
autonumber
'hide footbox
actor "Receptionist" as REP

participant ":RegisterTestUI" as UI
participant ":RegisterTestController" as CTRL
participant "Company" as COMP
participant "tstore:TestStore" as TS
participant "store: ClientStore" as CS
participant "ttstore: TestTypeStore" as TTS
participant ":ClientMapper" as MapperC
participant ":TestTypeMapper" as MapperTT
participant "pmcstore:ParameterCategoryStore" as PMCS
participant "pmstore:ParameterStore" as PMS
participant ":ParameterCategoryMapper" as MapperPMC
participant ":ParameterMapper" as MapperPM
participant "t: Test" as T
participant "TTS:List<TestType>"
participant "TTSDto:List<TestTypeDTO>"
participant "PMC:List<ParameterCategory>"
participant "PMCDto:List<ParameterCategoryDTO>"
participant "PM:List<Parameter>"
participant "PMDto:List<ParameterDTO>"

activate REP
REP -> UI : asks to register a test to be \n performed to a registered client
activate UI
UI --> REP : requests data (citizencardnumber,nhscode)
deactivate UI

REP -> UI : types requested data
activate UI

UI -> CTRL : CreateTest(citizencardnumber,nhscode)
activate CTRL

CTRL -> COMP : store = getClientStore()
activate COMP
deactivate COMP

CTRL -> CS : CL = getCitizencardnumber()
activate CS
deactivate CS
CTRL -> MapperC : CLDto = toDTO(CL)
activate MapperC
deactivate MapperC

CTRL -> COMP : tstore = getTestStore()
activate COMP
deactivate COMP
CTRL -> TS : t = CreateTest(citizencardnumber,nhscode)

activate TS
TS --> T**: create(citizencardnumber,nhscode)
deactivate TS

CTRL -> TS : validateTest(t)
activate TS
deactivate TS
deactivate CTRL

UI -> CTRL : TTSDto = getTestTypeList()

activate CTRL

CTRL -> COMP : ttstore = getTestTypeStore()
activate COMP
deactivate COMP

CTRL -> TTS : TTS = getTestTypeList()
activate TTS
deactivate TTS
CTRL -> MapperTT : TTSDto = toDTO(TTS)
activate MapperTT
deactivate MapperTT
deactivate CTRL


UI --> REP : shows test types and asks to select one
deactivate UI

REP -> UI : selects a test type
activate UI

UI -> CTRL : addParameterCategory(pmcld)

activate CTRL

CTRL -> TTS : pmc = getParameterCategory(pmcld)
activate TTS
deactivate TTS

CTRL -> T : b = addParameterCategory(pmc)
activate T
deactivate T
CTRL --> UI : ok
deactivate CTRL

UI --> REP : added with success

UI -> CTRL : PMCDto = getParameterCategoryList()

activate CTRL

CTRL -> COMP : pmcstore = getParameterCategoryStore()
activate COMP
deactivate COMP

CTRL -> PMCS : PMC = getParameterCategoryList()
activate PMCS
deactivate PMCS
CTRL -> MapperPMC : PMCDto = toDTO(PMC)
activate MapperPMC
deactivate MapperPMC
deactivate CTRL

UI --> REP : shows parameter categories to be selected
deactivate UI

REP -> UI : selects a parameter category
activate UI

UI -> CTRL : addTestType(ttld)

activate CTRL

CTRL -> TTS : tt = getTestType(ttld)
activate TTS
deactivate TTS

CTRL -> T : b = addTestType(tt)
activate T
deactivate T
CTRL --> UI : ok
deactivate CTRL

UI --> REP : added with success

UI -> CTRL : PMDto = getParameterList()

activate CTRL

CTRL -> COMP : pmstore = getParameterStore()
activate COMP
deactivate COMP

CTRL -> PMS : PM = getParameterList()
activate PMS
deactivate PMS
CTRL -> MapperPM : PMDto = toDTO(PM)
activate MapperPM
deactivate MapperPM
deactivate CTRL

UI --> REP : shows parameters to be selected
deactivate UI

loop
REP -> UI : selects a parameter
activate UI

UI -> CTRL : addParameter(pmld)

activate CTRL

CTRL -> PMS : pm = getParameter(pmld)
activate PMS
deactivate PMS

CTRL -> T : b = addParameter(pm)
activate T
deactivate T
CTRL --> UI : ok
deactivate CTRL

UI --> REP : added with success
end
UI --> REP : shows all data and requests confirmation
deactivate UI

|||

deactivate TS
deactivate COMP
deactivate CTRL
deactivate UI

REP -> UI : confirms the data
activate UI
UI -> CTRL : saveTest()
activate CTRL

CTRL -> TS : saveTest(t)
activate TS

TS -> TS: validateTest(t)
activate TS
deactivate TS
TS -> TS: generateTestCode(t)
activate TS
deactivate TS
TS -> TS: addTest(t)
activate TS
deactivate TS
deactivate TS

UI --> REP : informs operation success
deactivate TS
deactivate CTRL
deactivate UI

deactivate REP

@enduml