@startuml
'https://plantuml.com/class-diagram
class Administrator
class Company
class Employee
class Laboratory

Administrator -- Company : works for >
Employee -- Laboratory : works in >
Company -- Laboratory : owns >

@enduml