@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Administrator
class Company
class Employee
class User
class Role


class User{
-name
-email
-password
}
class Employee{
-name
-address
-phoneNumber
-email
-employeeId
-organizationRole
-socCode
}

class Role{
-id
-description
}
Administrator --|> Employee
Administrator "*"-"1" Company : works for >
Employee --|> User
Company "1"--"*" Employee : knows >
Administrator "1"--"*" Employee : register >
User "*"-"1" Role : plays >
@enduml