@startuml
autonumber
'hide footbox


participant ":Company" as Comp
participant "task : OperationTask" as Task
participant ":Timer" as Timer


-> Comp : scheduleOperation(delay,interval)
activate Comp

Comp -> Task** : create(ListOfTestsValidatedWithininterval)
Comp -> Timer** : create()
Comp -> Timer : schedule(task,delay,interval)
activate Timer
deactivate Timer
Timer -> Task : run()
ref over Task
SD_Run
end ref
activate Timer
activate Task
deactivate Task
deactivate Timer
deactivate Comp





@enduml