@startuml
skinparam classAttributeIconSize 0

class Client {
  -int citizen card number
  -int NHS number
  -int birth date
  -String sex
  -int TIF
  -int phone number
  -String e-mail
  -String name
  +Client(citizen card number, NHS number,\n birth date, sex, TIF, phone number, e-mail, name)
}

class Company {
  +getClientStore()
}

class ClientStore {
  +createClient(citizen card number, NHS number,\n birth date, sex, TIF, phone number, e-mail, name)
  +validateClient(cl)
  +saveClient(cl)
  +addClient(cl)
}

class CreateClientController {
  +createClient()
  +saveClient()
}

class CreateClientUI {

}

CreateClientUI ..> CreateClientController
CreateClientController ..> Company
CreateClientController ..> Client
CreateClientController ..> ClientStore
Company "1" -> "1" ClientStore : uses
ClientStore "1" -> "*" Client : register the



@enduml