@startuml
autonumber
actor "Receptionist" as OE

activate OE
OE -> ":System" : asks to register the client in the application
activate ":System"
":System" --> OE : requests data (citizen card number, NHS number, birth date, sex, TIF, phone number, e-mail, name)
deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : shows all data and requests confirmation
deactivate ":System"

OE -> ":System" : confirms the data
activate ":System"
":System" --> OE : informs operation success
deactivate ":System"

deactivate OE

@enduml